// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.Tasks.Data;
import ACL_Desktop.AppObject.DesktopSuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>extractdata</b><br>
 * Generated     : <b>2012/04/09 8:46:11 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  April 09, 2012
 * @author Steven_Xiang
 */
public abstract class extractdataHelper extends ACL_Desktop.AppObject.DesktopSuperHelper
{
	/**
	 * Extract: with default state.
	 *		.text : Extract
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : Extract
	 */
	protected TopLevelSubitemTestObject mainDialog() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mainDialog"));
	}
	/**
	 * Extract: with specific test context and state.
	 *		.text : Extract
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : Extract
	 */
	protected TopLevelSubitemTestObject mainDialog(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mainDialog"), anchor, flags);
	}
	
	

	protected extractdataHelper()
	{
		setScriptName("ACL_Desktop.Tasks.Data.extractdata");
	}
	
}

