// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.Tasks.Data;
import ACL_Desktop.AppObject.DesktopSuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>relatetables</b><br>
 * Generated     : <b>2012/03/16 5:49:19 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  March 16, 2012
 * @author Steven_Xiang
 */
public abstract class relatetablesHelper extends ACL_Desktop.AppObject.DesktopSuperHelper
{
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject gettingStarted_OK() 
	{
		return new GuiTestObject(
                        getMappedTestObject("gettingStarted_OK"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject gettingStarted_OK(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("gettingStarted_OK"), anchor, flags);
	}
	
	

	protected relatetablesHelper()
	{
		setScriptName("ACL_Desktop.Tasks.Data.relatetables");
	}
	
}

