// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.Tasks;
import ACL_Desktop.AppObject.DesktopSuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>filemenu</b><br>
 * Generated     : <b>2012/04/06 8:04:32 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  April 06, 2012
 * @author Steven_Xiang
 */
public abstract class filemenuHelper extends ACL_Desktop.AppObject.DesktopSuperHelper
{
	/**
	 * SysTreeView32: with default state.
	 *		.class : RegularExpression(SysTreeView32|\.Outline)
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_tree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_tree"));
	}
	/**
	 * SysTreeView32: with specific test context and state.
	 *		.class : RegularExpression(SysTreeView32|\.Outline)
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_tree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_tree"), anchor, flags);
	}
	
	/**
	 * cNoexsitngWorkbook_LOCALACLPathDoesNotExistPleaseVerifyTheCorrectPathWasGiven: with default state.
	 *		.class : .Statictext
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject cNoexsitngWorkbook_LOCALACLPat() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("cNoexsitngWorkbook_LOCALACLPat"));
	}
	/**
	 * cNoexsitngWorkbook_LOCALACLPathDoesNotExistPleaseVerifyTheCorrectPathWasGiven: with specific test context and state.
	 *		.class : .Statictext
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject cNoexsitngWorkbook_LOCALACLPat(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("cNoexsitngWorkbook_LOCALACLPat"), anchor, flags);
	}
	
	/**
	 * Cancel: with default state.
	 *		.text : Cancel
	 * 		.class : .Pushbutton
	 * 		.name : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiTestObject cancelDelete() 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancelDelete"));
	}
	/**
	 * Cancel: with specific test context and state.
	 *		.text : Cancel
	 * 		.class : .Pushbutton
	 * 		.name : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiTestObject cancelDelete(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancelDelete"), anchor, flags);
	}
	
	/**
	 * Cancel: with default state.
	 *		.text : Cancel
	 * 		.class : .Pushbutton
	 * 		.name : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiTestObject cancelRename() 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancelRename"));
	}
	/**
	 * Cancel: with specific test context and state.
	 *		.text : Cancel
	 * 		.class : .Pushbutton
	 * 		.name : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiTestObject cancelRename(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancelRename"), anchor, flags);
	}
	
	/**
	 * Delete: with default state.
	 *		.text : Delete
	 * 		.class : .Pushbutton
	 * 		.name : Delete
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okDelete() 
	{
		return new GuiTestObject(
                        getMappedTestObject("okDelete"));
	}
	/**
	 * Delete: with specific test context and state.
	 *		.text : Delete
	 * 		.class : .Pushbutton
	 * 		.name : Delete
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okDelete(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("okDelete"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okRename() 
	{
		return new GuiTestObject(
                        getMappedTestObject("okRename"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject okRename(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("okRename"), anchor, flags);
	}
	
	/**
	 * Ar: with default state.
	 *		.text : null
	 * 		.class : Edit
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject textSaveAs() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("textSaveAs"));
	}
	/**
	 * Ar: with specific test context and state.
	 *		.text : null
	 * 		.class : Edit
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject textSaveAs(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("textSaveAs"), anchor, flags);
	}
	
	/**
	 * Yes: with default state.
	 *		.text : Yes
	 * 		.class : .Pushbutton
	 * 		.name : Yes
	 * 		.classIndex : 0
	 */
	protected GuiTestObject yesbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("yesbutton"));
	}
	/**
	 * Yes: with specific test context and state.
	 *		.text : Yes
	 * 		.class : .Pushbutton
	 * 		.name : Yes
	 * 		.classIndex : 0
	 */
	protected GuiTestObject yesbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("yesbutton"), anchor, flags);
	}
	
	

	protected filemenuHelper()
	{
		setScriptName("ACL_Desktop.Tasks.filemenu");
	}
	
}

