// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.Tasks.Analyze.Statistical;
import ACL_Desktop.AppObject.DesktopSuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>profile</b><br>
 * Generated     : <b>2012/03/28 2:14:56 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  March 28, 2012
 * @author Steven_Xiang
 */
public abstract class profileHelper extends ACL_Desktop.AppObject.DesktopSuperHelper
{
	/**
	 * ProfileFields: with default state.
	 *		.text : Profile Fields
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : Profile Fields
	 */
	protected TopLevelSubitemTestObject mainDialog() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mainDialog"));
	}
	/**
	 * ProfileFields: with specific test context and state.
	 *		.text : Profile Fields
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : Profile Fields
	 */
	protected TopLevelSubitemTestObject mainDialog(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mainDialog"), anchor, flags);
	}
	
	

	protected profileHelper()
	{
		setScriptName("ACL_Desktop.Tasks.Analyze.Statistical.profile");
	}
	
}

