// DO NOT EDIT: This file is automatically generated each time the script is modified.
// To modify this file either use 'Insert Java Code Snippet'or 'Insert Java Method' 
// option from simplified script.
package ACL_Desktop.TestCase.Tools;

import resources.ACL_Desktop.TestCase.Tools.RunOldBatsHelper;
import com.rational.test.ft.*;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.value.*;
import com.rational.test.ft.vp.*;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;

// BEGIN custom imports 		
//TODO: Add custom imports here.
// END custom imports


public class RunOldBats extends RunOldBatsHelper
{
	/**
	 * Script Name   : <b>RunOldBats</b>
	 * Generated     : <b>2013-02-04 10:42:50 AM</b>
	 * Description   : Functional Test Script
	 * 
	 * @since  2013/02/04
	 * @author STEVEN_XIANG
	 */
	private String poolFile = "ACL_Desktop/DATA/KeywordTable/Tools/RunOldBats.xls";

	public void testMain(Object[] args) 
	{
		startFromLine = 2; // 4-9
		endAtLine =4;     //
	    exeTestCase(args);
	}
			
	public void onInitialize() {
		onInitialize(poolFile,getClass().getName());
	}
}