// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.Tasks.Tools;
import ACL_Desktop.AppObject.DesktopSuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>keywordDifinition</b><br>
 * Generated     : <b>2012/04/11 4:23:48 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  April 11, 2012
 * @author Steven_Xiang
 */
public abstract class keywordDifinitionHelper extends ACL_Desktop.AppObject.DesktopSuperHelper
{
	

	protected keywordDifinitionHelper()
	{
		setScriptName("ACL_Desktop.Tasks.Tools.keywordDifinition");
	}
	
}

