// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.Tasks.Tools;
import ACL_Desktop.AppObject.DesktopSuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>runScript</b><br>
 * Generated     : <b>2013/03/01 12:13:17 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  March 01, 2013
 * @author steven_xiang
 */
public abstract class runScriptHelper extends ACL_Desktop.AppObject.DesktopSuperHelper
{
	/**
	 * Workbook_DDWACLACL9: with default state.
	 *		.class : ACLMainFrame
	 * 		.processName : ACLWin.exe
	 */
	protected TopLevelSubitemTestObject ACL9() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ACL9"));
	}
	/**
	 * Workbook_DDWACLACL9: with specific test context and state.
	 *		.class : ACLMainFrame
	 * 		.processName : ACLWin.exe
	 */
	protected TopLevelSubitemTestObject ACL9(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ACL9"), anchor, flags);
	}
	
	/**
	 * ACL_StatusBar: with default state.
	 *		.text : null
	 * 		.class : ACL_StatusBar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_StatusBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_StatusBar"));
	}
	/**
	 * ACL_StatusBar: with specific test context and state.
	 *		.text : null
	 * 		.class : ACL_StatusBar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_StatusBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_StatusBar"), anchor, flags);
	}
	
	/**
	 * WhoShouldBeNotified: with default state.
	 *		.class : #32770
	 * 		.processName : ACLWin.exe
	 */
	protected TopLevelSubitemTestObject emailDialog() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("emailDialog"));
	}
	/**
	 * WhoShouldBeNotified: with specific test context and state.
	 *		.class : #32770
	 * 		.processName : ACLWin.exe
	 */
	protected TopLevelSubitemTestObject emailDialog(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("emailDialog"), anchor, flags);
	}
	
	/**
	 * Edit: with default state.
	 *		.text : Enter the e-mail address of user to send the results of the Test Batches to:
	 * 		.class : Edit
	 * 		.name : Enter the e-mail address of user to send the results of the Test Batches to:
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject emailbox() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("emailbox"));
	}
	/**
	 * Edit: with specific test context and state.
	 *		.text : Enter the e-mail address of user to send the results of the Test Batches to:
	 * 		.class : Edit
	 * 		.name : Enter the e-mail address of user to send the results of the Test Batches to:
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject emailbox(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("emailbox"), anchor, flags);
	}
	
	/**
	 * ListBox: with default state.
	 *		.class : ListBox
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject listBoxlist() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("listBoxlist"));
	}
	/**
	 * ListBox: with specific test context and state.
	 *		.class : ListBox
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject listBoxlist(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("listBoxlist"), anchor, flags);
	}
	
	/**
	 * DoScript: with default state.
	 *		.text : Do Script
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : Do Script
	 */
	protected TopLevelSubitemTestObject mainDialog() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mainDialog"));
	}
	/**
	 * DoScript: with specific test context and state.
	 *		.text : Do Script
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : Do Script
	 */
	protected TopLevelSubitemTestObject mainDialog(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mainDialog"), anchor, flags);
	}
	
	/**
	 * Statusbar: with default state.
	 *		.class : .Statusbar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject statusbarstatusBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("statusbarstatusBar"));
	}
	/**
	 * Statusbar: with specific test context and state.
	 *		.class : .Statusbar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject statusbarstatusBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("statusbarstatusBar"), anchor, flags);
	}
	
	

	protected runScriptHelper()
	{
		setScriptName("ACL_Desktop.Tasks.Tools.runScript");
	}
	
}

