// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.TestCase.Tools;
import lib.acl.helper.TestCaseSuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>RunOldBats</b><br>
 * Generated     : <b>2013/02/04 10:42:46 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  February 04, 2013
 * @author STEVEN_XIANG
 */
public abstract class RunOldBatsHelper extends lib.acl.helper.TestCaseSuperHelper
{
	

	protected RunOldBatsHelper()
	{
		setScriptName("ACL_Desktop.TestCase.Tools.RunOldBats");
	}
	
}

