// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.Tasks.Edit;
import ACL_Desktop.AppObject.DesktopSuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>variableAndFilter</b><br>
 * Generated     : <b>2012/04/04 5:24:01 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  April 04, 2012
 * @author Steven_Xiang
 */
public abstract class variableAndFilterHelper extends ACL_Desktop.AppObject.DesktopSuperHelper
{
	/**
	 * ListBox: with default state.
	 *		.class : ListBox
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject listBoxlist() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("listBoxlist"));
	}
	/**
	 * ListBox: with specific test context and state.
	 *		.class : ListBox
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject listBoxlist(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("listBoxlist"), anchor, flags);
	}
	
	/**
	 * Filters: with default state.
	 *		.text : RegularExpression(Filters|Variables)
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : RegularExpression(Filters|Variables)
	 */
	protected TopLevelSubitemTestObject mainDialog() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mainDialog"));
	}
	/**
	 * Filters: with specific test context and state.
	 *		.text : RegularExpression(Filters|Variables)
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : RegularExpression(Filters|Variables)
	 */
	protected TopLevelSubitemTestObject mainDialog(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mainDialog"), anchor, flags);
	}
	
	

	protected variableAndFilterHelper()
	{
		setScriptName("ACL_Desktop.Tasks.Edit.variableAndFilter");
	}
	
}

