// DO NOT EDIT: This file is automatically generated each time the script is modified.
// To modify this file either use 'Insert Java Code Snippet'or 'Insert Java Method' 
// option from simplified script.
package ACL_Desktop.AppObject;

import java.awt.Point;
import java.awt.Rectangle;
import java.util.ArrayList;

import lib.acl.helper.sup.LoggerHelper;
import lib.acl.helper.sup.ObjectHelper;

import resources.ACL_Desktop.AppObject.aclTableTabsHelper;
import ACL_Desktop.conf.beans.ProjectConf;

import com.rational.test.ft.*;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.value.*;
import com.rational.test.ft.vp.*;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;

// BEGIN custom imports 		
//TODO: Add custom imports here.
// END custom imports


public class aclTableTabs extends aclTableTabsHelper
{
	/**
	 * Script Name   : <b>aclTableTabs</b>
	 * Generated     : <b>2013-01-23 4:22:15 PM</b>
	 * Description   : Functional Test Script
	 * 
	 * @since  2013/01/23
	 * @author STEVEN_XIANG
	 */
	private ArrayList<String> tabList;	
//	private String wPage = DesktopSuperHelper.wPage;
//	private String wPageEn = DesktopSuperHelper.wPageEn;
	public aclTableTabs(){
		tabList = DesktopSuperHelper.tabList;
	}
	
	public void clear(){
		boolean ws = DesktopSuperHelper.keepWelcomeTab; // remove welcome page tab for L10N test - Steven
		tabList.clear();
		if(ws){
//			if(aclRoutines.cmd_to==null||!aclRoutines.cmd_to.exists()){
//		       new keywordUtil().invokeMenuCommand("Window->ShowWelcomeScreen");
//			}
		  tabList.add(DesktopSuperHelper.wPage);
		  verifyActiveTable( 0);
		  
		}else{
			DesktopSuperHelper.activeTab = -1;
		}
	}
	public void remove(){
 	   if(tabList.size()>1&&isTableItem(DesktopSuperHelper.activeTab)) // Suppose ws = true;
 	       remove(tabList.get(DesktopSuperHelper.activeTab));  
 	   else
 		   LoggerHelper.logTAFWarning("Have you opened any table yet?");
	}
	public void remove(String item){
	 	   if(tabList.contains(item)){
	 		   LoggerHelper.logInfo("Table tab "+item+" removed from desktop manager");
	 		   moveActiveTab(item);
	 	       tabList.remove(item);  
	 	      sleep(0);
	 	   }
		}	
	public void add(String item){
		add(item,"");
	}
	public void add(String item,String actOnTab){
//		if(!isTraceable(item))
//			return;
		if(!isTableItem(item))
			return;
		if(!tabList.contains(item)){
			LoggerHelper.logInfo("Table tab "+item+" added to document manager");
			String temp = "";
			if(DesktopSuperHelper.activeTab>-1){
			  temp = tabList.get(DesktopSuperHelper.activeTab);
			}
			  if(isTableItem(temp)&&isUnpined(temp)){
				remove(temp	);
				DesktopSuperHelper.activeTab += 1;
				tabList.add(DesktopSuperHelper.activeTab,item);
			  }else{
    		    tabList.add(item);
		        verifyActiveTable(tabList.size()-1);
			  }
			
			if(!actOnTab.equalsIgnoreCase("Close")){
				actOnTab(actOnTab,item);
			}
		}else{
			verifyActiveTable( tabList.indexOf(item));
			if(actOnTab.equalsIgnoreCase("Close")){
				actOnTab(actOnTab,item);
			}
		}
	}
	
	public void handleWpage(){
		if(!DesktopSuperHelper.keepWelcomeTab){
		   //if(DesktopSuperHelper.activeTab<0){
		   if(tabList.size()==0){
			     clickCloseTab(DesktopSuperHelper.wPage);
			     sleep(2);
			     clickCloseTab(DesktopSuperHelper.wPage);
		   }
		}
				
	}
	public boolean isLast(int index){
		return index==tabList.size()-1;
	}
	public String getLast(){
		return tabList.get(tabList.size()-1);
	}
	public boolean isActive(int index){
		return index==DesktopSuperHelper.activeTab;
	}
	public boolean isActive(String tab){
		return isActive(tabList.indexOf(tab));
	}
	public void moveActiveTab(String tab){
		   int index = tabList.indexOf(tab); 		   
 		   if(isActive(index)){
 			   if(isLast(index)){
 				  verifyActiveTable( index-1);
 			   }
 		   }
 		 //  verifyTabStatus(tab);
	}
	
	public String getTableStatus(String item){
		   if(!isTableItem(item)){
			   //LoggerHelper.logTAFWarning("There is no status for the "+wPage);
			   return "Not a table";
		   }
		   //
		return DesktopSuperHelper.getTableStatus(ACL10(),acl_StatusBar(),item);
	}
	public boolean verifyTabStatus(String item){		
       boolean found = false;
	   String tableStatus = getTableStatus(item);
	   if( tableStatus.equals("Not a table")){
		   found = true;
		   return found;
	   }
	   if(tableStatus.matches("(?i)"+item+"\\|.*")){
		   found = true;
		   LoggerHelper.logTAFInfo(item+" has been opened/activated successfully.");
	   }else if(tableStatus.matches("(?i)"+"\\|.*")||  // This is in case any automation issue, remove it if it's stable enough then - Steven
			   tableStatus.equals("")){
		   found = true;
		   LoggerHelper.logTAFWarning("Failed to open/activate table '"+item+"'?");
	   }else{
		   found = false;
		   LoggerHelper.logTAFWarning("Failed to open/activate table '"+item+"'? current active item is '"+tableStatus+"'");
	   }
	   return found;
	}
	
	public void verifyActiveTable(int activeIndex){
		if(activeIndex<0){
			DesktopSuperHelper.activeTab = -1;
			return;
		}
		if(verifyTabStatus(tabList.get(activeIndex))){
		  DesktopSuperHelper.activeTab = activeIndex;
		}
	}
	public void switchTableTabs(){
	
	   for(String tab:tabList){
	       switchToTab(tab);
	   }
	}
 	 //************  Pin Tab ***********
	
	public boolean actOnTab(String act){
		return actOnTab(act,getLast());
	}
    public boolean actOnTab(String act,String item){
    	
		if(act.equals("")){
			if(ProjectConf.pinTable){
				act="Pin";
			}else{
			  return true;
			}
		}
		if(act.equalsIgnoreCase("Pin"))
			return pinTab(item);
		else if(act.equalsIgnoreCase("Close"))
		    return closeTab(item);
		else{
			LoggerHelper.logTAFWarning("Action on tab - '"+act+"' is not supported currently!");
		}
		return true;
	}
	 public boolean pinTab(){
	       return pinTab(getLast());
	 	 }	
 	 public boolean pinTab(String tab){
        boolean done = false;
        if(!isTraceable(tab))
        	return false;
        if(!isPined(tab)){
           ObjectHelper.click(tabCtrlwindow(),getTabPoint(tab,-8),"Pin[/Unpin] "+tab);
        }
        
 	   return done;
 	 }
 	 public boolean unpinTab(String tab){
         boolean done = false;
         if(!isTraceable(tab))
         	return false;
         if(isPined(tab)){
            ObjectHelper.click(tabCtrlwindow(),getTabPoint(tab,-8),"Unpin[/Pin] "+tab);
         }
  	   return done;
  	 } 	 
 	 public boolean isUnpined(String tab){
 		if(ProjectConf.testType.equalsIgnoreCase("Server")){
 			return true;
 		}
 		     return false;
 	 // Enable this if isPined works properly
 	 //        return !isPined(tab);
 	 }
 	 public boolean isPined(String tab){
 		 boolean pined = true;
 		 if(ProjectConf.testType.equalsIgnoreCase("Server")){
 			 // Pin doesn't work for server table
 			 pined = false;
 		 }else {
 			 pined = true;
 		 }
        //
//TBD ..... Steven - need to capture the icon, then return pined instead false;	  		  		 
// 		 return pined;
 		 return false;
 	 }
 	 //********* Close Tab ***********
     public boolean closeTab(){
      return closeTab(getLast());
	 }
	 
     public boolean clickCloseTab(String tab){
    	 if(!tabCtrlwindow().exists())
    		 return true;
    	 try{    		
    	    ObjectHelper.click(tabCtrlwindow(),getCloseTabPoint(),"Close Tab "+tab);
    	    remove(tab);
    	    return true;
    	 }catch(Exception e){
    	    	return false;
    	    }
     }
	 public boolean closeTab(String tab){
       boolean done = true;
       if(!isActive(tabList.indexOf(tab)))
	       done = switchToTab(tab);
       
       done = clickCloseTab(tab);	   
	   return done;
	 }
  	 
	 public boolean switchToTab(String tab){
	   boolean done = false;
	   ObjectHelper.click(tabCtrlwindow(),getTabPoint(tab,-50),tab);
	   
	   verifyActiveTable( tabList.indexOf(tab));	   
	   //verifyTabStatus(tab);
	   return done;
	 }
	 
	 public Point getCloseTabPoint(){
		 int y = 0,x=0;		 
		 Rectangle rec =tabCtrlwindow().getScreenRectangle();
		 x = rec.width -15;
		 y = rec.height/2;
		 
		 return new Point(x,y);
	 }
	 public Point getTabPoint(String tab,int x){
		 int dev = x;
		 int y=8,lspace = 6;
		 int index = tabList.indexOf(tab);

		 for(int i=0;i<=index;i++){
			 String temp = tabList.get(i);			 
			 x += lengthOf(temp,isActive(i));
			 if(i==0){
				 x += lspace;
			 }
			 LoggerHelper.logTAFDebug("\t\tLOOP:"+temp+" - x = "+(x-dev) );
		 }
		 LoggerHelper.logTAFDebug(tab+" - x = "+(x-dev) );
		 return new Point(x,y);
	 }

	 //*******  defined for table tab tracing *************
     public String[][] tableTab ={{DesktopSuperHelper.wPage,"87","93"},
				{"Inventory","86","98"},
				{"Trans","69","73"},
				{"Ap_Trans","88","95"},
				{"Payroll","74","80"},
				{"Inventory2","92","105"},
				{"Vendor","77","81"},
				{"Sales_Reps","99","106"},
				{"Dept","65","68"},
				{"Customer","86","96"},
				{"Empmast","85","94"},
				{"Work_Depts","102","111"},
				{"Inventory_saveas","126","145"},
				{"Inventory_renamed","133","156"},
				{"TBD","0","0"},
		};
     //*****************************************************
     
     public boolean isTraceable(String tab){
    	 boolean traceable = false;
 		for(int i=0;i<tableTab.length;i++){
			if(tab.equalsIgnoreCase(tableTab[i][0])){
				return true;
			}
		}
 		return traceable;
     }
     public boolean isTableItem(int index){
    	 return isTableItem(tabList.get(index));
     }
     public boolean isTableItem(String tab){
    	 boolean isTable = false;
    	 if(!(tab==null)
    			 &&!("".equals(tab.trim()))
    			 &&!(tab.equalsIgnoreCase(DesktopSuperHelper.wPage)
    					 ||tab.equalsIgnoreCase(DesktopSuperHelper.wPageLoc))
    			 ){
    				 isTable = true;
    			 }
    	 return isTable;
     }
	 public int lengthOf(String tab,boolean active){
		 int index = 1;
		 int bytes = tab.getBytes().length;
		 int pointsPerByte = 5, icon = 22, pin = 20 + 1; //Actual Icon(15,12),Actual Pin(14,14)
		 if(active){
			 index =2;
			 pointsPerByte = 6;
		 }

		
		for(int i=0;i<tableTab.length;i++){
			if(tab.equalsIgnoreCase(tableTab[i][0])){
				return Integer.parseInt(tableTab[i][index]);
			}
		}
		LoggerHelper.logTAFDebug("Pin point tab "+tab+" may fail due to wrong point clicked");
		return icon + bytes*pointsPerByte + pin;
	 }
	public void testMain(Object[] args) 
	{
	}
}
		