// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.AppObject;
import lib.acl.helper.sup.ObjectHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>aclRoutines</b><br>
 * Generated     : <b>2012/11/16 2:10:10 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  November 16, 2012
 * @author Steven_Xiang
 */
public abstract class aclRoutinesHelper extends lib.acl.helper.sup.ObjectHelper
{
	/**
	 * Workbook_DDWACLACL9: with default state.
	 *		.class : ACLMainFrame
	 * 		.processName : ACLWin.exe
	 */
	protected TopLevelSubitemTestObject ACL_Win() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ACL_Win"));
	}
	/**
	 * Workbook_DDWACLACL9: with specific test context and state.
	 *		.class : ACLMainFrame
	 * 		.processName : ACLWin.exe
	 */
	protected TopLevelSubitemTestObject ACL_Win(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ACL_Win"), anchor, flags);
	}
	
	/**
	 * TableProperties: with default state.
	 *		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : RegularExpression(Table Properties|Project Properties)
	 */
	protected TopLevelSubitemTestObject Properties() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Properties"));
	}
	/**
	 * TableProperties: with specific test context and state.
	 *		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : RegularExpression(Table Properties|Project Properties)
	 */
	protected TopLevelSubitemTestObject Properties(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("Properties"), anchor, flags);
	}
	
	/**
	 * ACL_CommandLine_WND: with default state.
	 *		.text : null
	 * 		.class : ACL_CommandLine_WND
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acL_CommandLine() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acL_CommandLine"));
	}
	/**
	 * ACL_CommandLine_WND: with specific test context and state.
	 *		.text : null
	 * 		.class : ACL_CommandLine_WND
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acL_CommandLine(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acL_CommandLine"), anchor, flags);
	}
	
	/**
	 * ACL_CmdLine_ClearBtn: with default state.
	 *		.text : ACL_CmdLine_ClearBtn
	 * 		.class : .Pushbutton
	 * 		.name : ACL_CmdLine_ClearBtn
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_CmdLine_Clear() 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_CmdLine_Clear"));
	}
	/**
	 * ACL_CmdLine_ClearBtn: with specific test context and state.
	 *		.text : ACL_CmdLine_ClearBtn
	 * 		.class : .Pushbutton
	 * 		.name : ACL_CmdLine_ClearBtn
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_CmdLine_Clear(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_CmdLine_Clear"), anchor, flags);
	}
	
	/**
	 * ACL_CmdLine_DlgBtn: with default state.
	 *		.text : ACL_CmdLine_DlgBtn
	 * 		.class : .Pushbutton
	 * 		.name : ACL_CmdLine_DlgBtn
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_CmdLine_Edit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_CmdLine_Edit"));
	}
	/**
	 * ACL_CmdLine_DlgBtn: with specific test context and state.
	 *		.text : ACL_CmdLine_DlgBtn
	 * 		.class : .Pushbutton
	 * 		.name : ACL_CmdLine_DlgBtn
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_CmdLine_Edit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_CmdLine_Edit"), anchor, flags);
	}
	
	/**
	 * ACL_CmdLine_RunBtn: with default state.
	 *		.text : ACL_CmdLine_RunBtn
	 * 		.class : .Pushbutton
	 * 		.name : ACL_CmdLine_RunBtn
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_CmdLine_Run() 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_CmdLine_Run"));
	}
	/**
	 * ACL_CmdLine_RunBtn: with specific test context and state.
	 *		.text : ACL_CmdLine_RunBtn
	 * 		.class : .Pushbutton
	 * 		.name : ACL_CmdLine_RunBtn
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_CmdLine_Run(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_CmdLine_Run"), anchor, flags);
	}
	
	/**
	 * ACL_CmdLine_Edit: with default state.
	 *		.class : ACL_CmdLine_Edit
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_CmdLine_Text() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CmdLine_Text"));
	}
	/**
	 * ACL_CmdLine_Edit: with specific test context and state.
	 *		.class : ACL_CmdLine_Edit
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_CmdLine_Text(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CmdLine_Text"), anchor, flags);
	}
	
	/**
	 * Pushbutton: with default state.
	 *		.text : null
	 * 		.class : .Pushbutton
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_Filter_Clear() 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_Filter_Clear"));
	}
	/**
	 * Pushbutton: with specific test context and state.
	 *		.text : null
	 * 		.class : .Pushbutton
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_Filter_Clear(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_Filter_Clear"), anchor, flags);
	}
	
	/**
	 * Pushbutton: with default state.
	 *		.text : null
	 * 		.class : .Pushbutton
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_Filter_Edit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_Filter_Edit"));
	}
	/**
	 * Pushbutton: with specific test context and state.
	 *		.text : null
	 * 		.class : .Pushbutton
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_Filter_Edit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_Filter_Edit"), anchor, flags);
	}
	
	/**
	 * Pushbutton: with default state.
	 *		.text : null
	 * 		.class : .Pushbutton
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_Filter_Run() 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_Filter_Run"));
	}
	/**
	 * Pushbutton: with specific test context and state.
	 *		.text : null
	 * 		.class : .Pushbutton
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_Filter_Run(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_Filter_Run"), anchor, flags);
	}
	
	/**
	 * Edit: with default state.
	 *		.text : Filter:
	 * 		.class : Edit
	 * 		.name : Filter:
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject acl_Filter_Text() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("acl_Filter_Text"));
	}
	/**
	 * Edit: with specific test context and state.
	 *		.text : Filter:
	 * 		.class : Edit
	 * 		.name : Filter:
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject acl_Filter_Text(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("acl_Filter_Text"), anchor, flags);
	}
	
	/**
	 * ShowCommandLine: with default state.
	 *		.text : Show Command Line
	 * 		.class : .Menuitem
	 * 		.name : Show Command Line
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_ShowCommandLine() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ShowCommandLine"));
	}
	/**
	 * ShowCommandLine: with specific test context and state.
	 *		.text : Show Command Line
	 * 		.class : .Menuitem
	 * 		.name : Show Command Line
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_ShowCommandLine(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ShowCommandLine"), anchor, flags);
	}
	
	/**
	 * WTL_SplitterWindow: with default state.
	 *		.text : null
	 * 		.class : WTL_SplitterWindow
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_SplitterWin() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_SplitterWin"));
	}
	/**
	 * WTL_SplitterWindow: with specific test context and state.
	 *		.text : null
	 * 		.class : WTL_SplitterWindow
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_SplitterWin(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_SplitterWin"), anchor, flags);
	}
	
	/**
	 * ACL_TabNavigator_WND: with default state.
	 *		.text : ACL_TabNavigator_WND
	 * 		.class : WTL_DotNetTabCtrl
	 * 		.name : ACL_TabNavigator_WND
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_TabNavigator() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_TabNavigator"));
	}
	/**
	 * ACL_TabNavigator_WND: with specific test context and state.
	 *		.text : ACL_TabNavigator_WND
	 * 		.class : WTL_DotNetTabCtrl
	 * 		.name : ACL_TabNavigator_WND
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_TabNavigator(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_TabNavigator"), anchor, flags);
	}
	
	/**
	 * SysTreeView32: with default state.
	 *		.class : RegularExpression(SysTreeView32|\.Outline)
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_Tree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Tree"));
	}
	/**
	 * SysTreeView32: with specific test context and state.
	 *		.class : RegularExpression(SysTreeView32|\.Outline)
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_Tree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Tree"), anchor, flags);
	}
	
	/**
	 * Scrollbar: with default state.
	 *		.class : .Scrollbar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_TreeBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_TreeBar"));
	}
	/**
	 * Scrollbar: with specific test context and state.
	 *		.class : .Scrollbar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_TreeBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_TreeBar"), anchor, flags);
	}
	
	/**
	 * ACL_Overview_Tree: with default state.
	 *		.text : null
	 * 		.class : ACL_Overview_Tree
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_Treewin() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Treewin"));
	}
	/**
	 * ACL_Overview_Tree: with specific test context and state.
	 *		.text : null
	 * 		.class : ACL_Overview_Tree
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_Treewin(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Treewin"), anchor, flags);
	}
	
	/**
	 * Window: with default state.
	 *		.text : Window
	 * 		.class : .Menuitem
	 * 		.name : Window
	 * 		.classIndex : 8
	 */
	protected GuiSubitemTestObject acl_Window() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Window"));
	}
	/**
	 * Window: with specific test context and state.
	 *		.text : Window
	 * 		.class : .Menuitem
	 * 		.name : Window
	 * 		.classIndex : 8
	 */
	protected GuiSubitemTestObject acl_Window(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Window"), anchor, flags);
	}
	
	/**
	 * ContentPaneClient: with default state.
	 *		.text : null
	 * 		.class : ContentPaneClient
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_contentPane() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_contentPane"));
	}
	/**
	 * ContentPaneClient: with specific test context and state.
	 *		.text : null
	 * 		.class : ContentPaneClient
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_contentPane(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_contentPane"), anchor, flags);
	}
	
	/**
	 * DocumentManager: with default state.
	 *		.text : null
	 * 		.class : DocumentManager
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_docManager() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_docManager"));
	}
	/**
	 * DocumentManager: with specific test context and state.
	 *		.text : null
	 * 		.class : DocumentManager
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_docManager(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_docManager"), anchor, flags);
	}
	
	/**
	 * _DataFile: with default state.
	 *		.text : Location:
	 * 		.class : Edit
	 * 		.name : Location:
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject prop_Location() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("prop_Location"));
	}
	/**
	 * _DataFile: with specific test context and state.
	 *		.text : Location:
	 * 		.class : Edit
	 * 		.name : Location:
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject prop_Location(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("prop_Location"), anchor, flags);
	}
	
	/**
	 * _DataFileInventoryFil: with default state.
	 *		.class : .Statictext
	 * 		.name : Modified:
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject prop_Modified() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("prop_Modified"));
	}
	/**
	 * _DataFileInventoryFil: with specific test context and state.
	 *		.class : .Statictext
	 * 		.name : Modified:
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject prop_Modified(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("prop_Modified"), anchor, flags);
	}
	
	/**
	 * NotApplicable: with default state.
	 *		.class : .Statictext
	 * 		.name : Name:
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject prop_Name() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("prop_Name"));
	}
	/**
	 * NotApplicable: with specific test context and state.
	 *		.class : .Statictext
	 * 		.name : Name:
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject prop_Name(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("prop_Name"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject prop_OK() 
	{
		return new GuiTestObject(
                        getMappedTestObject("prop_OK"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.text : OK
	 * 		.class : .Pushbutton
	 * 		.name : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject prop_OK(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("prop_OK"), anchor, flags);
	}
	
	

	protected aclRoutinesHelper()
	{
		setScriptName("ACL_Desktop.AppObject.aclRoutines");
	}
	
}

