// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.AppObject;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>aclTableTabs</b><br>
 * Generated     : <b>2013/01/30 4:26:47 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  January 30, 2013
 * @author STEVEN_XIANG
 */
public abstract class aclTableTabsHelper extends RationalTestScript
{
	/**
	 * Workbook_DDWACLACL9: with default state.
	 *		.class : ACLMainFrame
	 * 		.processName : ACLWin.exe
	 */
	protected TopLevelSubitemTestObject ACL10() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ACL10"));
	}
	/**
	 * Workbook_DDWACLACL9: with specific test context and state.
	 *		.class : ACLMainFrame
	 * 		.processName : ACLWin.exe
	 */
	protected TopLevelSubitemTestObject ACL10(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ACL10"), anchor, flags);
	}
	
	/**
	 * ACL_StatusBar: with default state.
	 *		.text : null
	 * 		.class : ACL_StatusBar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_StatusBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_StatusBar"));
	}
	/**
	 * ACL_StatusBar: with specific test context and state.
	 *		.text : null
	 * 		.class : ACL_StatusBar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_StatusBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_StatusBar"), anchor, flags);
	}
	
	/**
	 * WTL_DotNetTabCtrl: with default state.
	 *		.text : null
	 * 		.class : WTL_DotNetTabCtrl
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject tabCtrlwindow() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("tabCtrlwindow"));
	}
	/**
	 * WTL_DotNetTabCtrl: with specific test context and state.
	 *		.text : null
	 * 		.class : WTL_DotNetTabCtrl
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject tabCtrlwindow(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("tabCtrlwindow"), anchor, flags);
	}
	
	

	protected aclTableTabsHelper()
	{
		setScriptName("ACL_Desktop.AppObject.aclTableTabs");
	}
	
}

