// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.AppObject;
import lib.acl.helper.sup.ObjectHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>getObjects</b><br>
 * Generated     : <b>2012/10/24 3:19:58 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  October 24, 2012
 * @author Steven_Xiang
 */
public abstract class getObjectsHelper extends lib.acl.helper.sup.ObjectHelper
{
	/**
	 * Workbook_DDWACLACL9: with default state.
	 *		.class : ACLMainFrame
	 * 		.processName : ACLWin.exe
	 */
	protected TopLevelSubitemTestObject ACL9window() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ACL9window"));
	}
	/**
	 * Workbook_DDWACLACL9: with specific test context and state.
	 *		.class : ACLMainFrame
	 * 		.processName : ACLWin.exe
	 */
	protected TopLevelSubitemTestObject ACL9window(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ACL9window"), anchor, flags);
	}
	
	/**
	 * ACL_CmdLine_Edit: with default state.
	 *		.class : ACL_CmdLine_Edit
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acL_CmdLine_Editwindow() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acL_CmdLine_Editwindow"));
	}
	/**
	 * ACL_CmdLine_Edit: with specific test context and state.
	 *		.class : ACL_CmdLine_Edit
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acL_CmdLine_Editwindow(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acL_CmdLine_Editwindow"), anchor, flags);
	}
	
	/**
	 * ActivityLog: with default state.
	 *		.text : Activity Log...
	 * 		.class : .Menuitem
	 * 		.name : Activity Log...
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject acl_ActivityLog() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ActivityLog"));
	}
	/**
	 * ActivityLog: with specific test context and state.
	 *		.text : Activity Log...
	 * 		.class : .Menuitem
	 * 		.name : Activity Log...
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject acl_ActivityLog(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ActivityLog"), anchor, flags);
	}
	
	/**
	 * Age: with default state.
	 *		.text : Age...
	 * 		.class : .Menuitem
	 * 		.name : Age...
	 * 		.classIndex : 6
	 */
	protected GuiSubitemTestObject acl_Age() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Age"));
	}
	/**
	 * Age: with specific test context and state.
	 *		.text : Age...
	 * 		.class : .Menuitem
	 * 		.name : Age...
	 * 		.classIndex : 6
	 */
	protected GuiSubitemTestObject acl_Age(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Age"), anchor, flags);
	}
	
	/**
	 * Analyze: with default state.
	 *		.text : Analyze
	 * 		.class : .Menuitem
	 * 		.name : Analyze
	 * 		.classIndex : 3
	 */
	protected GuiSubitemTestObject acl_Analyze() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Analyze"));
	}
	/**
	 * Analyze: with specific test context and state.
	 *		.text : Analyze
	 * 		.class : .Menuitem
	 * 		.name : Analyze
	 * 		.classIndex : 3
	 */
	protected GuiSubitemTestObject acl_Analyze(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Analyze"), anchor, flags);
	}
	
	/**
	 * Applications: with default state.
	 *		.text : Applications
	 * 		.class : .Menuitem
	 * 		.name : Applications
	 * 		.classIndex : 5
	 */
	protected GuiSubitemTestObject acl_Applications() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Applications"));
	}
	/**
	 * Applications: with specific test context and state.
	 *		.text : Applications
	 * 		.class : .Menuitem
	 * 		.name : Applications
	 * 		.classIndex : 5
	 */
	protected GuiSubitemTestObject acl_Applications(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Applications"), anchor, flags);
	}
	
	/**
	 * CalculateSampleSize: with default state.
	 *		.text : Calculate Sample Size...
	 * 		.class : .Menuitem
	 * 		.name : Calculate Sample Size...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_CalculateSampleSize() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CalculateSampleSize"));
	}
	/**
	 * CalculateSampleSize: with specific test context and state.
	 *		.text : Calculate Sample Size...
	 * 		.class : .Menuitem
	 * 		.name : Calculate Sample Size...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_CalculateSampleSize(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CalculateSampleSize"), anchor, flags);
	}
	
	/**
	 * Classify: with default state.
	 *		.text : Classify...
	 * 		.class : .Menuitem
	 * 		.name : Classify...
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject acl_Classify() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Classify"));
	}
	/**
	 * Classify: with specific test context and state.
	 *		.text : Classify...
	 * 		.class : .Menuitem
	 * 		.name : Classify...
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject acl_Classify(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Classify"), anchor, flags);
	}
	
	/**
	 * ClearHistory: with default state.
	 *		.text : Clear History
	 * 		.class : .Menuitem
	 * 		.name : Clear History
	 */
	protected GuiSubitemTestObject acl_ClearHistory() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ClearHistory"));
	}
	/**
	 * ClearHistory: with specific test context and state.
	 *		.text : Clear History
	 * 		.class : .Menuitem
	 * 		.name : Clear History
	 */
	protected GuiSubitemTestObject acl_ClearHistory(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ClearHistory"), anchor, flags);
	}
	
	/**
	 * CloseProject: with default state.
	 *		.text : Close Project
	 * 		.class : .Menuitem
	 * 		.name : Close Project
	 * 		.classIndex : 7
	 */
	protected GuiSubitemTestObject acl_CloseProject() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CloseProject"));
	}
	/**
	 * CloseProject: with specific test context and state.
	 *		.text : Close Project
	 * 		.class : .Menuitem
	 * 		.name : Close Project
	 * 		.classIndex : 7
	 */
	protected GuiSubitemTestObject acl_CloseProject(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CloseProject"), anchor, flags);
	}
	
	/**
	 * Connect: with default state.
	 *		.text : Connect...
	 * 		.class : .Menuitem
	 * 		.name : Connect...
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_Connect() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Connect"));
	}
	/**
	 * Connect: with specific test context and state.
	 *		.text : Connect...
	 * 		.class : .Menuitem
	 * 		.name : Connect...
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_Connect(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Connect"), anchor, flags);
	}
	
	/**
	 * CountRecordsCtrl3: with default state.
	 *		.text : Count Records... Ctrl+3
	 * 		.class : .Menuitem
	 * 		.name : Count Records... Ctrl+3
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_CountRecords() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CountRecords"));
	}
	/**
	 * CountRecordsCtrl3: with specific test context and state.
	 *		.text : Count Records... Ctrl+3
	 * 		.class : .Menuitem
	 * 		.name : Count Records... Ctrl+3
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_CountRecords(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CountRecords"), anchor, flags);
	}
	
	/**
	 * CreateIndex: with default state.
	 *		.text : Create Index...
	 * 		.class : .Menuitem
	 * 		.name : Create Index...
	 * 		.classIndex : 3
	 */
	protected GuiSubitemTestObject acl_CreateIndex() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CreateIndex"));
	}
	/**
	 * CreateIndex: with specific test context and state.
	 *		.text : Create Index...
	 * 		.class : .Menuitem
	 * 		.name : Create Index...
	 * 		.classIndex : 3
	 */
	protected GuiSubitemTestObject acl_CreateIndex(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CreateIndex"), anchor, flags);
	}
	
	/**
	 * CreateTemplate: with default state.
	 *		.text : Create Template...
	 * 		.class : .Menuitem
	 * 		.name : Create Template...
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_CreateTemplate() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CreateTemplate"));
	}
	/**
	 * CreateTemplate: with specific test context and state.
	 *		.text : Create Template...
	 * 		.class : .Menuitem
	 * 		.name : Create Template...
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_CreateTemplate(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CreateTemplate"), anchor, flags);
	}
	
	/**
	 * CrossTabulate: with default state.
	 *		.text : Cross-tabulate...
	 * 		.class : .Menuitem
	 * 		.name : Cross-tabulate...
	 * 		.classIndex : 8
	 */
	protected GuiSubitemTestObject acl_CrossTabulate() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CrossTabulate"));
	}
	/**
	 * CrossTabulate: with specific test context and state.
	 *		.text : Cross-tabulate...
	 * 		.class : .Menuitem
	 * 		.name : Cross-tabulate...
	 * 		.classIndex : 8
	 */
	protected GuiSubitemTestObject acl_CrossTabulate(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CrossTabulate"), anchor, flags);
	}
	
	/**
	 * CrystalReports: with default state.
	 *		.text : Crystal Reports
	 * 		.class : .Menuitem
	 * 		.name : Crystal Reports
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_CrystalReports() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CrystalReports"));
	}
	/**
	 * CrystalReports: with specific test context and state.
	 *		.text : Crystal Reports
	 * 		.class : .Menuitem
	 * 		.name : Crystal Reports
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_CrystalReports(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_CrystalReports"), anchor, flags);
	}
	
	/**
	 * Data: with default state.
	 *		.text : Data
	 * 		.class : .Menuitem
	 * 		.name : Data
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_Data() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Data"));
	}
	/**
	 * Data: with specific test context and state.
	 *		.text : Data
	 * 		.class : .Menuitem
	 * 		.name : Data
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_Data(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Data"), anchor, flags);
	}
	
	/**
	 * DatabaseProfiles: with default state.
	 *		.text : Database Profiles...
	 * 		.class : .Menuitem
	 * 		.name : Database Profiles...
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_DatabaseProfiles() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_DatabaseProfiles"));
	}
	/**
	 * DatabaseProfiles: with specific test context and state.
	 *		.text : Database Profiles...
	 * 		.class : .Menuitem
	 * 		.name : Database Profiles...
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_DatabaseProfiles(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_DatabaseProfiles"), anchor, flags);
	}
	
	/**
	 * Delete: with default state.
	 *		.text : Delete
	 * 		.class : .Menuitem
	 * 		.name : Delete
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_Delete() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Delete"));
	}
	/**
	 * Delete: with specific test context and state.
	 *		.text : Delete
	 * 		.class : .Menuitem
	 * 		.name : Delete
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_Delete(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Delete"), anchor, flags);
	}
	
	/**
	 * DeleteAllNotesFromTable: with default state.
	 *		.text : Delete All Notes from Table
	 * 		.class : .Menuitem
	 * 		.name : Delete All Notes from Table
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_DeleteAllNotesFromTable() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_DeleteAllNotesFromTable"));
	}
	/**
	 * DeleteAllNotesFromTable: with specific test context and state.
	 *		.text : Delete All Notes from Table
	 * 		.class : .Menuitem
	 * 		.name : Delete All Notes from Table
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_DeleteAllNotesFromTable(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_DeleteAllNotesFromTable"), anchor, flags);
	}
	
	/**
	 * Disconnect: with default state.
	 *		.text : Disconnect...
	 * 		.class : .Menuitem
	 * 		.name : Disconnect...
	 * 		.classIndex : 3
	 */
	protected GuiSubitemTestObject acl_Disconnect() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Disconnect"));
	}
	/**
	 * Disconnect: with specific test context and state.
	 *		.text : Disconnect...
	 * 		.class : .Menuitem
	 * 		.name : Disconnect...
	 * 		.classIndex : 3
	 */
	protected GuiSubitemTestObject acl_Disconnect(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Disconnect"), anchor, flags);
	}
	
	/**
	 * DocumentManager: with default state.
	 *		.text : null
	 * 		.class : DocumentManager
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_DocManager() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_DocManager"));
	}
	/**
	 * DocumentManager: with specific test context and state.
	 *		.text : null
	 * 		.class : DocumentManager
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_DocManager(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_DocManager"), anchor, flags);
	}
	
	/**
	 * WTL_DotNetTabCtrl: with default state.
	 *		.text : null
	 * 		.class : WTL_DotNetTabCtrl
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_DocTitleBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_DocTitleBar"));
	}
	/**
	 * WTL_DotNetTabCtrl: with specific test context and state.
	 *		.text : null
	 * 		.class : WTL_DotNetTabCtrl
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_DocTitleBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_DocTitleBar"), anchor, flags);
	}
	
	/**
	 * Edit: with default state.
	 *		.text : Edit
	 * 		.class : .Menuitem
	 * 		.name : Edit
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_Edit() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Edit"));
	}
	/**
	 * Edit: with specific test context and state.
	 *		.text : Edit
	 * 		.class : .Menuitem
	 * 		.name : Edit
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_Edit(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Edit"), anchor, flags);
	}
	
	/**
	 * EditNote: with default state.
	 *		.text : Edit Note...
	 * 		.class : .Menuitem
	 * 		.name : Edit Note...
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_EditNote() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_EditNote"));
	}
	/**
	 * EditNote: with specific test context and state.
	 *		.text : Edit Note...
	 * 		.class : .Menuitem
	 * 		.name : Edit Note...
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_EditNote(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_EditNote"), anchor, flags);
	}
	
	/**
	 * EvaluateError: with default state.
	 *		.text : Evaluate Error...
	 * 		.class : .Menuitem
	 * 		.name : Evaluate Error...
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_EvaluateError() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_EvaluateError"));
	}
	/**
	 * EvaluateError: with specific test context and state.
	 *		.text : Evaluate Error...
	 * 		.class : .Menuitem
	 * 		.name : Evaluate Error...
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_EvaluateError(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_EvaluateError"), anchor, flags);
	}
	
	/**
	 * ExamineSequenceCtrl6: with default state.
	 *		.text : Examine Sequence... Ctrl+6
	 * 		.class : .Menuitem
	 * 		.name : Examine Sequence... Ctrl+6
	 * 		.classIndex : 10
	 */
	protected GuiSubitemTestObject acl_ExamineSequence() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ExamineSequence"));
	}
	/**
	 * ExamineSequenceCtrl6: with specific test context and state.
	 *		.text : Examine Sequence... Ctrl+6
	 * 		.class : .Menuitem
	 * 		.name : Examine Sequence... Ctrl+6
	 * 		.classIndex : 10
	 */
	protected GuiSubitemTestObject acl_ExamineSequence(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ExamineSequence"), anchor, flags);
	}
	
	/**
	 * ExportToOtherApplication: with default state.
	 *		.text : Export To Other Application...
	 * 		.class : .Menuitem
	 * 		.name : Export To Other Application...
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_ExportToApp() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ExportToApp"));
	}
	/**
	 * ExportToOtherApplication: with specific test context and state.
	 *		.text : Export To Other Application...
	 * 		.class : .Menuitem
	 * 		.name : Export To Other Application...
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_ExportToApp(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ExportToApp"), anchor, flags);
	}
	
	/**
	 * ExtractData: with default state.
	 *		.text : Extract Data...
	 * 		.class : .Menuitem
	 * 		.name : Extract Data...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_ExtractData() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ExtractData"));
	}
	/**
	 * ExtractData: with specific test context and state.
	 *		.text : Extract Data...
	 * 		.class : .Menuitem
	 * 		.name : Extract Data...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_ExtractData(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ExtractData"), anchor, flags);
	}
	
	/**
	 * File: with default state.
	 *		.text : File
	 * 		.class : .Menuitem
	 * 		.name : File
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_File() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_File"));
	}
	/**
	 * File: with specific test context and state.
	 *		.text : File
	 * 		.class : .Menuitem
	 * 		.name : File
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_File(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_File"), anchor, flags);
	}
	
	/**
	 * Filters: with default state.
	 *		.text : Filters...
	 * 		.class : .Menuitem
	 * 		.name : Filters...
	 * 		.classIndex : 6
	 */
	protected GuiSubitemTestObject acl_Filters() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Filters"));
	}
	/**
	 * Filters: with specific test context and state.
	 *		.text : Filters...
	 * 		.class : .Menuitem
	 * 		.name : Filters...
	 * 		.classIndex : 6
	 */
	protected GuiSubitemTestObject acl_Filters(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Filters"), anchor, flags);
	}
	
	/**
	 * FuzzyDuplicates: with default state.
	 *		.text : Fuzzy Duplicates
	 * 		.class : .Menuitem
	 * 		.name : Fuzzy Duplicates
	 * 		.classIndex : 13
	 */
	protected GuiSubitemTestObject acl_FuzzyDuplicates() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_FuzzyDuplicates"));
	}
	/**
	 * FuzzyDuplicates: with specific test context and state.
	 *		.text : Fuzzy Duplicates
	 * 		.class : .Menuitem
	 * 		.name : Fuzzy Duplicates
	 * 		.classIndex : 13
	 */
	protected GuiSubitemTestObject acl_FuzzyDuplicates(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_FuzzyDuplicates"), anchor, flags);
	}
	
	/**
	 * Help: with default state.
	 *		.text : Help
	 * 		.class : .Menuitem
	 * 		.name : Help
	 * 		.classIndex : 9
	 */
	protected GuiSubitemTestObject acl_Help() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Help"));
	}
	/**
	 * Help: with specific test context and state.
	 *		.text : Help
	 * 		.class : .Menuitem
	 * 		.name : Help
	 * 		.classIndex : 9
	 */
	protected GuiSubitemTestObject acl_Help(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Help"), anchor, flags);
	}
	
	/**
	 * HistogramCtrl8: with default state.
	 *		.text : Histogram... Ctrl+8
	 * 		.class : .Menuitem
	 * 		.name : Histogram... Ctrl+8
	 * 		.classIndex : 5
	 */
	protected GuiSubitemTestObject acl_Histogram() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Histogram"));
	}
	/**
	 * HistogramCtrl8: with specific test context and state.
	 *		.text : Histogram... Ctrl+8
	 * 		.class : .Menuitem
	 * 		.name : Histogram... Ctrl+8
	 * 		.classIndex : 5
	 */
	protected GuiSubitemTestObject acl_Histogram(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Histogram"), anchor, flags);
	}
	
	/**
	 * JoinTablesCtrl7: with default state.
	 *		.text : Join Tables... Ctrl+7
	 * 		.class : .Menuitem
	 * 		.name : Join Tables... Ctrl+7
	 * 		.classIndex : 6
	 */
	protected GuiSubitemTestObject acl_JoinTables() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_JoinTables"));
	}
	/**
	 * JoinTablesCtrl7: with specific test context and state.
	 *		.text : Join Tables... Ctrl+7
	 * 		.class : .Menuitem
	 * 		.name : Join Tables... Ctrl+7
	 * 		.classIndex : 6
	 */
	protected GuiSubitemTestObject acl_JoinTables(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_JoinTables"), anchor, flags);
	}
	
	/**
	 * LookForDuplicates: with default state.
	 *		.text : Look for Duplicates...
	 * 		.class : .Menuitem
	 * 		.name : Look for Duplicates...
	 * 		.classIndex : 12
	 */
	protected GuiSubitemTestObject acl_LookForDuplicates() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_LookForDuplicates"));
	}
	/**
	 * LookForDuplicates: with specific test context and state.
	 *		.text : Look for Duplicates...
	 * 		.class : .Menuitem
	 * 		.name : Look for Duplicates...
	 * 		.classIndex : 12
	 */
	protected GuiSubitemTestObject acl_LookForDuplicates(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_LookForDuplicates"), anchor, flags);
	}
	
	/**
	 * LookForGaps: with default state.
	 *		.text : Look for Gaps...
	 * 		.class : .Menuitem
	 * 		.name : Look for Gaps...
	 * 		.classIndex : 11
	 */
	protected GuiSubitemTestObject acl_LookForGaps() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_LookForGaps"));
	}
	/**
	 * LookForGaps: with specific test context and state.
	 *		.text : Look for Gaps...
	 * 		.class : .Menuitem
	 * 		.name : Look for Gaps...
	 * 		.classIndex : 11
	 */
	protected GuiSubitemTestObject acl_LookForGaps(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_LookForGaps"), anchor, flags);
	}
	
	/**
	 * MergeTables: with default state.
	 *		.text : Merge Tables...
	 * 		.class : .Menuitem
	 * 		.name : Merge Tables...
	 * 		.classIndex : 7
	 */
	protected GuiSubitemTestObject acl_MergeTables() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_MergeTables"));
	}
	/**
	 * MergeTables: with specific test context and state.
	 *		.text : Merge Tables...
	 * 		.class : .Menuitem
	 * 		.name : Merge Tables...
	 * 		.classIndex : 7
	 */
	protected GuiSubitemTestObject acl_MergeTables(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_MergeTables"), anchor, flags);
	}
	
	/**
	 * New: with default state.
	 *		.text : New
	 * 		.class : .Menuitem
	 * 		.name : New
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_New() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_New"));
	}
	/**
	 * New: with specific test context and state.
	 *		.text : New
	 * 		.class : .Menuitem
	 * 		.name : New
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_New(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_New"), anchor, flags);
	}
	
	/**
	 * Folder: with default state.
	 *		.text : Folder...
	 * 		.class : .Menuitem
	 * 		.name : Folder...
	 * 		.classIndex : 3
	 */
	protected GuiSubitemTestObject acl_NewFolder() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_NewFolder"));
	}
	/**
	 * Folder: with specific test context and state.
	 *		.text : Folder...
	 * 		.class : .Menuitem
	 * 		.name : Folder...
	 * 		.classIndex : 3
	 */
	protected GuiSubitemTestObject acl_NewFolder(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_NewFolder"), anchor, flags);
	}
	
	/**
	 * Project: with default state.
	 *		.text : Project...
	 * 		.class : .Menuitem
	 * 		.name : Project...
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject acl_NewProject() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_NewProject"));
	}
	/**
	 * Project: with specific test context and state.
	 *		.text : Project...
	 * 		.class : .Menuitem
	 * 		.name : Project...
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject acl_NewProject(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_NewProject"), anchor, flags);
	}
	
	/**
	 * Script: with default state.
	 *		.text : Script...
	 * 		.class : .Menuitem
	 * 		.name : Script...
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_NewScript() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_NewScript"));
	}
	/**
	 * Script: with specific test context and state.
	 *		.text : Script...
	 * 		.class : .Menuitem
	 * 		.name : Script...
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_NewScript(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_NewScript"), anchor, flags);
	}
	
	/**
	 * Table: with default state.
	 *		.text : Table...
	 * 		.class : .Menuitem
	 * 		.name : Table...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_NewTable() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_NewTable"));
	}
	/**
	 * Table: with specific test context and state.
	 *		.text : Table...
	 * 		.class : .Menuitem
	 * 		.name : Table...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_NewTable(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_NewTable"), anchor, flags);
	}
	
	/**
	 * Workspace: with default state.
	 *		.text : Workspace...
	 * 		.class : .Menuitem
	 * 		.name : Workspace...
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_NewWorkspace() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_NewWorkspace"));
	}
	/**
	 * Workspace: with specific test context and state.
	 *		.text : Workspace...
	 * 		.class : .Menuitem
	 * 		.name : Workspace...
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_NewWorkspace(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_NewWorkspace"), anchor, flags);
	}
	
	/**
	 * Notes: with default state.
	 *		.text : Notes
	 * 		.class : .Menuitem
	 * 		.name : Notes
	 * 		.classIndex : 8
	 */
	protected GuiSubitemTestObject acl_Notes() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Notes"));
	}
	/**
	 * Notes: with specific test context and state.
	 *		.text : Notes
	 * 		.class : .Menuitem
	 * 		.name : Notes
	 * 		.classIndex : 8
	 */
	protected GuiSubitemTestObject acl_Notes(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Notes"), anchor, flags);
	}
	
	/**
	 * OpenProjectCtrlO: with default state.
	 *		.text : Open Project... Ctrl+O
	 * 		.class : .Menuitem
	 * 		.name : Open Project... Ctrl+O
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject acl_OpenProject() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_OpenProject"));
	}
	/**
	 * OpenProjectCtrlO: with specific test context and state.
	 *		.text : Open Project... Ctrl+O
	 * 		.class : .Menuitem
	 * 		.name : Open Project... Ctrl+O
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject acl_OpenProject(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_OpenProject"), anchor, flags);
	}
	
	/**
	 * Options: with default state.
	 *		.text : Options...
	 * 		.class : .Menuitem
	 * 		.name : Options...
	 * 		.classIndex : 10
	 */
	protected GuiSubitemTestObject acl_Options() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Options"));
	}
	/**
	 * Options: with specific test context and state.
	 *		.text : Options...
	 * 		.class : .Menuitem
	 * 		.name : Options...
	 * 		.classIndex : 10
	 */
	protected GuiSubitemTestObject acl_Options(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Options"), anchor, flags);
	}
	
	/**
	 * PageSetup: with default state.
	 *		.text : Page Setup...
	 * 		.class : .Menuitem
	 * 		.name : Page Setup...
	 * 		.classIndex : 10
	 */
	protected GuiSubitemTestObject acl_PageSetup() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_PageSetup"));
	}
	/**
	 * PageSetup: with specific test context and state.
	 *		.text : Page Setup...
	 * 		.class : .Menuitem
	 * 		.name : Page Setup...
	 * 		.classIndex : 10
	 */
	protected GuiSubitemTestObject acl_PageSetup(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_PageSetup"), anchor, flags);
	}
	
	/**
	 * PerformBenfordAnalysis: with default state.
	 *		.text : Perform Benford Analysis...
	 * 		.class : .Menuitem
	 * 		.name : Perform Benford Analysis...
	 * 		.classIndex : 9
	 */
	protected GuiSubitemTestObject acl_PerformBenfordAnalysis() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_PerformBenfordAnalysis"));
	}
	/**
	 * PerformBenfordAnalysis: with specific test context and state.
	 *		.text : Perform Benford Analysis...
	 * 		.class : .Menuitem
	 * 		.name : Perform Benford Analysis...
	 * 		.classIndex : 9
	 */
	protected GuiSubitemTestObject acl_PerformBenfordAnalysis(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_PerformBenfordAnalysis"), anchor, flags);
	}
	
	/**
	 * PrintPreview: with default state.
	 *		.text : Print Preview
	 * 		.class : .Menuitem
	 * 		.name : Print Preview
	 * 		.classIndex : 12
	 */
	protected GuiSubitemTestObject acl_PrintPreview() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_PrintPreview"));
	}
	/**
	 * PrintPreview: with specific test context and state.
	 *		.text : Print Preview
	 * 		.class : .Menuitem
	 * 		.name : Print Preview
	 * 		.classIndex : 12
	 */
	protected GuiSubitemTestObject acl_PrintPreview(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_PrintPreview"), anchor, flags);
	}
	
	/**
	 * Profile: with default state.
	 *		.text : Profile...
	 * 		.class : .Menuitem
	 * 		.name : Profile...
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_Profile() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Profile"));
	}
	/**
	 * Profile: with specific test context and state.
	 *		.text : Profile...
	 * 		.class : .Menuitem
	 * 		.name : Profile...
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_Profile(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Profile"), anchor, flags);
	}
	
	/**
	 * Properties: with default state.
	 *		.text : Properties...
	 * 		.class : .Menuitem
	 * 		.name : Properties...
	 * 		.classIndex : 3
	 */
	protected GuiSubitemTestObject acl_Properties() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Properties"));
	}
	/**
	 * Properties: with specific test context and state.
	 *		.text : Properties...
	 * 		.class : .Menuitem
	 * 		.name : Properties...
	 * 		.classIndex : 3
	 */
	protected GuiSubitemTestObject acl_Properties(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Properties"), anchor, flags);
	}
	
	/**
	 * RecentProjects: with default state.
	 *		.text : Recent Projects
	 * 		.class : .Menupopup
	 * 		.name : Recent Projects
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_RPSMenu() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_RPSMenu"));
	}
	/**
	 * RecentProjects: with specific test context and state.
	 *		.text : Recent Projects
	 * 		.class : .Menupopup
	 * 		.name : Recent Projects
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_RPSMenu(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_RPSMenu"), anchor, flags);
	}
	
	/**
	 * RecentProjects: with default state.
	 *		.text : Recent Projects
	 * 		.class : .Menuitem
	 * 		.name : Recent Projects
	 * 		.classIndex : 14
	 */
	protected GuiSubitemTestObject acl_RecentProjects() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_RecentProjects"));
	}
	/**
	 * RecentProjects: with specific test context and state.
	 *		.text : Recent Projects
	 * 		.class : .Menuitem
	 * 		.name : Recent Projects
	 * 		.classIndex : 14
	 */
	protected GuiSubitemTestObject acl_RecentProjects(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_RecentProjects"), anchor, flags);
	}
	
	/**
	 * RelateTables: with default state.
	 *		.text : Relate Tables...
	 * 		.class : .Menuitem
	 * 		.name : Relate Tables...
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject acl_RelateTables() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_RelateTables"));
	}
	/**
	 * RelateTables: with specific test context and state.
	 *		.text : Relate Tables...
	 * 		.class : .Menuitem
	 * 		.name : Relate Tables...
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject acl_RelateTables(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_RelateTables"), anchor, flags);
	}
	
	/**
	 * Rename: with default state.
	 *		.text : Rename
	 * 		.class : .Menuitem
	 * 		.name : Rename
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_Rename() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Rename"));
	}
	/**
	 * Rename: with specific test context and state.
	 *		.text : Rename
	 * 		.class : .Menuitem
	 * 		.name : Rename
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_Rename(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Rename"), anchor, flags);
	}
	
	/**
	 * ReportCtrlR: with default state.
	 *		.text : Report... Ctrl+R
	 * 		.class : .Menuitem
	 * 		.name : Report... Ctrl+R
	 * 		.classIndex : 5
	 */
	protected GuiSubitemTestObject acl_Report() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Report"));
	}
	/**
	 * ReportCtrlR: with specific test context and state.
	 *		.text : Report... Ctrl+R
	 * 		.class : .Menuitem
	 * 		.name : Report... Ctrl+R
	 * 		.classIndex : 5
	 */
	protected GuiSubitemTestObject acl_Report(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Report"), anchor, flags);
	}
	
	/**
	 * RunScriptCtrl1: with default state.
	 *		.text : Run Script... Ctrl+1
	 * 		.class : .Menuitem
	 * 		.name : Run Script... Ctrl+1
	 * 		.classIndex : 7
	 */
	protected GuiSubitemTestObject acl_RunScript() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_RunScript"));
	}
	/**
	 * RunScriptCtrl1: with specific test context and state.
	 *		.text : Run Script... Ctrl+1
	 * 		.class : .Menuitem
	 * 		.name : Run Script... Ctrl+1
	 * 		.classIndex : 7
	 */
	protected GuiSubitemTestObject acl_RunScript(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_RunScript"), anchor, flags);
	}
	
	/**
	 * SampleRecordsCtrl9: with default state.
	 *		.text : Sample Records... Ctrl+9
	 * 		.class : .Menuitem
	 * 		.name : Sample Records... Ctrl+9
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_SampleRecords() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_SampleRecords"));
	}
	/**
	 * SampleRecordsCtrl9: with specific test context and state.
	 *		.text : Sample Records... Ctrl+9
	 * 		.class : .Menuitem
	 * 		.name : Sample Records... Ctrl+9
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_SampleRecords(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_SampleRecords"), anchor, flags);
	}
	
	/**
	 * Sampling: with default state.
	 *		.text : Sampling
	 * 		.class : .Menuitem
	 * 		.name : Sampling
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject acl_Sampling() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Sampling"));
	}
	/**
	 * Sampling: with specific test context and state.
	 *		.text : Sampling
	 * 		.class : .Menuitem
	 * 		.name : Sampling
	 * 		.classIndex : 4
	 */
	protected GuiSubitemTestObject acl_Sampling(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Sampling"), anchor, flags);
	}
	
	/**
	 * Save: with default state.
	 *		.text : Save
	 * 		.class : .Menuitem
	 * 		.name : Save
	 * 		.classIndex : 8
	 */
	protected GuiSubitemTestObject acl_Save() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Save"));
	}
	/**
	 * Save: with specific test context and state.
	 *		.text : Save
	 * 		.class : .Menuitem
	 * 		.name : Save
	 * 		.classIndex : 8
	 */
	protected GuiSubitemTestObject acl_Save(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Save"), anchor, flags);
	}
	
	/**
	 * SaveAs: with default state.
	 *		.text : Save As..
	 * 		.class : .Menuitem
	 * 		.name : Save As..
	 * 		.classIndex : 9
	 */
	protected GuiSubitemTestObject acl_SaveAs() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_SaveAs"));
	}
	/**
	 * SaveAs: with specific test context and state.
	 *		.text : Save As..
	 * 		.class : .Menuitem
	 * 		.name : Save As..
	 * 		.classIndex : 9
	 */
	protected GuiSubitemTestObject acl_SaveAs(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_SaveAs"), anchor, flags);
	}
	
	/**
	 * SaveProjectCtrlS: with default state.
	 *		.text : Save Project Ctrl+S
	 * 		.class : .Menuitem
	 * 		.name : Save Project Ctrl+S
	 * 		.classIndex : 5
	 */
	protected GuiSubitemTestObject acl_SaveProject() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_SaveProject"));
	}
	/**
	 * SaveProjectCtrlS: with specific test context and state.
	 *		.text : Save Project Ctrl+S
	 * 		.class : .Menuitem
	 * 		.name : Save Project Ctrl+S
	 * 		.classIndex : 5
	 */
	protected GuiSubitemTestObject acl_SaveProject(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_SaveProject"), anchor, flags);
	}
	
	/**
	 * SaveProjectAs: with default state.
	 *		.text : Save Project As...
	 * 		.class : .Menuitem
	 * 		.name : Save Project As...
	 * 		.classIndex : 6
	 */
	protected GuiSubitemTestObject acl_SaveProjectAs() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_SaveProjectAs"));
	}
	/**
	 * SaveProjectAs: with specific test context and state.
	 *		.text : Save Project As...
	 * 		.class : .Menuitem
	 * 		.name : Save Project As...
	 * 		.classIndex : 6
	 */
	protected GuiSubitemTestObject acl_SaveProjectAs(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_SaveProjectAs"), anchor, flags);
	}
	
	/**
	 * Server: with default state.
	 *		.text : Server
	 * 		.class : .Menuitem
	 * 		.name : Server
	 * 		.classIndex : 7
	 */
	protected GuiSubitemTestObject acl_Server() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Server"));
	}
	/**
	 * Server: with specific test context and state.
	 *		.text : Server
	 * 		.class : .Menuitem
	 * 		.name : Server
	 * 		.classIndex : 7
	 */
	protected GuiSubitemTestObject acl_Server(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Server"), anchor, flags);
	}
	
	/**
	 * ServerProfiles: with default state.
	 *		.text : Server Profiles...
	 * 		.class : .Menuitem
	 * 		.name : Server Profiles...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_ServerProfiles() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ServerProfiles"));
	}
	/**
	 * ServerProfiles: with specific test context and state.
	 *		.text : Server Profiles...
	 * 		.class : .Menuitem
	 * 		.name : Server Profiles...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_ServerProfiles(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ServerProfiles"), anchor, flags);
	}
	
	/**
	 * ShowCommandLine: with default state.
	 *		.text : Show Command Line
	 * 		.class : .Menuitem
	 * 		.name : Show Command Line
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_ShowCommandLine() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ShowCommandLine"));
	}
	/**
	 * ShowCommandLine: with specific test context and state.
	 *		.text : Show Command Line
	 * 		.class : .Menuitem
	 * 		.name : Show Command Line
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_ShowCommandLine(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ShowCommandLine"), anchor, flags);
	}
	
	/**
	 * SortRecords: with default state.
	 *		.text : Sort Records...
	 * 		.class : .Menuitem
	 * 		.name : Sort Records...
	 * 		.classIndex : 8
	 */
	protected GuiSubitemTestObject acl_SortRecords() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_SortRecords"));
	}
	/**
	 * SortRecords: with specific test context and state.
	 *		.text : Sort Records...
	 * 		.class : .Menuitem
	 * 		.name : Sort Records...
	 * 		.classIndex : 8
	 */
	protected GuiSubitemTestObject acl_SortRecords(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_SortRecords"), anchor, flags);
	}
	
	/**
	 * Statistical: with default state.
	 *		.text : Statistical
	 * 		.class : .Menuitem
	 * 		.name : Statistical
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_Statistical() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Statistical"));
	}
	/**
	 * Statistical: with specific test context and state.
	 *		.text : Statistical
	 * 		.class : .Menuitem
	 * 		.name : Statistical
	 * 		.classIndex : 2
	 */
	protected GuiSubitemTestObject acl_Statistical(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Statistical"), anchor, flags);
	}
	
	/**
	 * Statistical: with default state.
	 *		.text : Statistical
	 * 		.class : .Menupopup
	 * 		.name : Statistical
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_Statistical_2() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Statistical_2"));
	}
	/**
	 * Statistical: with specific test context and state.
	 *		.text : Statistical
	 * 		.class : .Menupopup
	 * 		.name : Statistical
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_Statistical_2(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Statistical_2"), anchor, flags);
	}
	
	/**
	 * Statistics: with default state.
	 *		.text : Statistics...
	 * 		.class : .Menuitem
	 * 		.name : Statistics...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_Statistics() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Statistics"));
	}
	/**
	 * Statistics: with specific test context and state.
	 *		.text : Statistics...
	 * 		.class : .Menuitem
	 * 		.name : Statistics...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_Statistics(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Statistics"), anchor, flags);
	}
	
	/**
	 * StratifyCtrl5: with default state.
	 *		.text : Stratify... Ctrl+5
	 * 		.class : .Menuitem
	 * 		.name : Stratify... Ctrl+5
	 * 		.classIndex : 3
	 */
	protected GuiSubitemTestObject acl_Stratify() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Stratify"));
	}
	/**
	 * StratifyCtrl5: with specific test context and state.
	 *		.text : Stratify... Ctrl+5
	 * 		.class : .Menuitem
	 * 		.name : Stratify... Ctrl+5
	 * 		.classIndex : 3
	 */
	protected GuiSubitemTestObject acl_Stratify(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Stratify"), anchor, flags);
	}
	
	/**
	 * SummarizeCtrl0: with default state.
	 *		.text : Summarize... Ctrl+0
	 * 		.class : .Menuitem
	 * 		.name : Summarize... Ctrl+0
	 * 		.classIndex : 7
	 */
	protected GuiSubitemTestObject acl_Summarize() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Summarize"));
	}
	/**
	 * SummarizeCtrl0: with specific test context and state.
	 *		.text : Summarize... Ctrl+0
	 * 		.class : .Menuitem
	 * 		.name : Summarize... Ctrl+0
	 * 		.classIndex : 7
	 */
	protected GuiSubitemTestObject acl_Summarize(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Summarize"), anchor, flags);
	}
	
	/**
	 * Tools: with default state.
	 *		.text : Tools
	 * 		.class : .Menuitem
	 * 		.name : Tools
	 * 		.classIndex : 6
	 */
	protected GuiSubitemTestObject acl_Tools() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Tools"));
	}
	/**
	 * Tools: with specific test context and state.
	 *		.text : Tools
	 * 		.class : .Menuitem
	 * 		.name : Tools
	 * 		.classIndex : 6
	 */
	protected GuiSubitemTestObject acl_Tools(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Tools"), anchor, flags);
	}
	
	/**
	 * TotalFieldsCtrl4: with default state.
	 *		.text : Total Fields... Ctrl+4
	 * 		.class : .Menuitem
	 * 		.name : Total Fields... Ctrl+4
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_TotalFields() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_TotalFields"));
	}
	/**
	 * TotalFieldsCtrl4: with specific test context and state.
	 *		.text : Total Fields... Ctrl+4
	 * 		.class : .Menuitem
	 * 		.name : Total Fields... Ctrl+4
	 * 		.classIndex : 1
	 */
	protected GuiSubitemTestObject acl_TotalFields(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_TotalFields"), anchor, flags);
	}
	
	/**
	 * UpdateTemplate: with default state.
	 *		.text : Update Template...
	 * 		.class : .Menuitem
	 * 		.name : Update Template...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_UpdateTemplate() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_UpdateTemplate"));
	}
	/**
	 * UpdateTemplate: with specific test context and state.
	 *		.text : Update Template...
	 * 		.class : .Menuitem
	 * 		.name : Update Template...
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_UpdateTemplate(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_UpdateTemplate"), anchor, flags);
	}
	
	/**
	 * Variables: with default state.
	 *		.text : Variables...
	 * 		.class : .Menuitem
	 * 		.name : Variables...
	 * 		.classIndex : 7
	 */
	protected GuiSubitemTestObject acl_Variables() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Variables"));
	}
	/**
	 * Variables: with specific test context and state.
	 *		.text : Variables...
	 * 		.class : .Menuitem
	 * 		.name : Variables...
	 * 		.classIndex : 7
	 */
	protected GuiSubitemTestObject acl_Variables(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Variables"), anchor, flags);
	}
	
	/**
	 * Verify: with default state.
	 *		.text : Verify...
	 * 		.class : .Menuitem
	 * 		.name : Verify...
	 * 		.classIndex : 9
	 */
	protected GuiSubitemTestObject acl_Verify() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Verify"));
	}
	/**
	 * Verify: with specific test context and state.
	 *		.text : Verify...
	 * 		.class : .Menuitem
	 * 		.name : Verify...
	 * 		.classIndex : 9
	 */
	protected GuiSubitemTestObject acl_Verify(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Verify"), anchor, flags);
	}
	
	/**
	 * Window: with default state.
	 *		.text : Window
	 * 		.class : .Menuitem
	 * 		.name : Window
	 * 		.classIndex : 8
	 */
	protected GuiSubitemTestObject acl_Window() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Window"));
	}
	/**
	 * Window: with specific test context and state.
	 *		.text : Window
	 * 		.class : .Menuitem
	 * 		.name : Window
	 * 		.classIndex : 8
	 */
	protected GuiSubitemTestObject acl_Window(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_Window"), anchor, flags);
	}
	
	/**
	 * Toolbar: with default state.
	 *		.class : .Toolbar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_menuBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_menuBar"));
	}
	/**
	 * Toolbar: with specific test context and state.
	 *		.class : .Toolbar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_menuBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_menuBar"), anchor, flags);
	}
	
	/**
	 * ViewDefault_ViewDataFileEmpmastFil: with default state.
	 *		.text : RegularExpression(View:.*)
	 * 		.class : OldGrid
	 * 		.name : RegularExpression(View:.*)
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_viewGrid() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_viewGrid"));
	}
	/**
	 * ViewDefault_ViewDataFileEmpmastFil: with specific test context and state.
	 *		.text : RegularExpression(View:.*)
	 * 		.class : OldGrid
	 * 		.name : RegularExpression(View:.*)
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_viewGrid(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_viewGrid"), anchor, flags);
	}
	
	

	protected getObjectsHelper()
	{
		setScriptName("ACL_Desktop.AppObject.getObjects");
	}
	
}

