// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.AppObject;
import lib.acl.helper.sup.ObjectHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>keywordUtil</b><br>
 * Generated     : <b>2012/02/28 2:04:07 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  February 28, 2012
 * @author Steven_Xiang
 */
public abstract class keywordUtilHelper extends lib.acl.helper.sup.ObjectHelper
{
	/**
	 * Workbook_DDWACLACL9: with default state.
	 *		.class : ACLMainFrame
	 * 		.processName : ACLWin.exe
	 */
	protected TopLevelSubitemTestObject ACL9window() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ACL9window"));
	}
	/**
	 * Workbook_DDWACLACL9: with specific test context and state.
	 *		.class : ACLMainFrame
	 * 		.processName : ACLWin.exe
	 */
	protected TopLevelSubitemTestObject ACL9window(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("ACL9window"), anchor, flags);
	}
	
	/**
	 * Cancel: with default state.
	 *		.text : Cancel
	 * 		.class : .Pushbutton
	 * 		.name : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_CrashCancel() 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_CrashCancel"));
	}
	/**
	 * Cancel: with specific test context and state.
	 *		.text : Cancel
	 * 		.class : .Pushbutton
	 * 		.name : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_CrashCancel(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_CrashCancel"), anchor, flags);
	}
	
	/**
	 * Send: with default state.
	 *		.text : Send
	 * 		.class : .Pushbutton
	 * 		.name : Send
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_CrashSend() 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_CrashSend"));
	}
	/**
	 * Send: with specific test context and state.
	 *		.text : Send
	 * 		.class : .Pushbutton
	 * 		.name : Send
	 * 		.classIndex : 0
	 */
	protected GuiTestObject acl_CrashSend(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("acl_CrashSend"), anchor, flags);
	}
	
	/**
	 * ACL: with default state.
	 *		.text : ACL
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : ACL
	 */
	protected TopLevelSubitemTestObject acl_CrashWin() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("acl_CrashWin"));
	}
	/**
	 * ACL: with specific test context and state.
	 *		.text : ACL
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : ACL
	 */
	protected TopLevelSubitemTestObject acl_CrashWin(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("acl_CrashWin"), anchor, flags);
	}
	
	/**
	 * Toolbar: with default state.
	 *		.class : .Toolbar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_MenuBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_MenuBar"));
	}
	/**
	 * Toolbar: with specific test context and state.
	 *		.class : .Toolbar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_MenuBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_MenuBar"), anchor, flags);
	}
	
	/**
	 * ATL009CBCC8: with default state.
	 *		.text : null
	 * 		.class : RegularExpression(ATL:*)
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_ProjectPane() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ProjectPane"));
	}
	/**
	 * ATL009CBCC8: with specific test context and state.
	 *		.text : null
	 * 		.class : RegularExpression(ATL:*)
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_ProjectPane(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_ProjectPane"), anchor, flags);
	}
	
	/**
	 * RecentProjects: with default state.
	 *		.text : Recent Projects
	 * 		.class : .Menupopup
	 * 		.name : Recent Projects
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_RPCMenu() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_RPCMenu"));
	}
	/**
	 * RecentProjects: with specific test context and state.
	 *		.text : Recent Projects
	 * 		.class : .Menupopup
	 * 		.name : Recent Projects
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_RPCMenu(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_RPCMenu"), anchor, flags);
	}
	
	/**
	 * SysTreeView32: with default state.
	 *		.class : RegularExpression(SysTreeView32|.Outline)
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_sysTree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_sysTree"));
	}
	/**
	 * SysTreeView32: with specific test context and state.
	 *		.class : RegularExpression(SysTreeView32|.Outline)
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject acl_sysTree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("acl_sysTree"), anchor, flags);
	}
	
	/**
	 * WTL_CommandBar: with default state.
	 *		.text : null
	 * 		.class : WTL_CommandBar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject commandBar() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("commandBar"));
	}
	/**
	 * WTL_CommandBar: with specific test context and state.
	 *		.text : null
	 * 		.class : WTL_CommandBar
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject commandBar(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("commandBar"), anchor, flags);
	}
	
	/**
	 * Cancel: with default state.
	 *		.text : Cancel
	 * 		.class : .Pushbutton
	 * 		.name : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiTestObject sp_activity_cancel() 
	{
		return new GuiTestObject(
                        getMappedTestObject("sp_activity_cancel"));
	}
	/**
	 * Cancel: with specific test context and state.
	 *		.text : Cancel
	 * 		.class : .Pushbutton
	 * 		.name : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiTestObject sp_activity_cancel(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("sp_activity_cancel"), anchor, flags);
	}
	
	/**
	 * Cancel: with default state.
	 *		.text : Cancel
	 * 		.class : Button
	 * 		.name : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject sp_activity_cancelwindow() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("sp_activity_cancelwindow"));
	}
	/**
	 * Cancel: with specific test context and state.
	 *		.text : Cancel
	 * 		.class : Button
	 * 		.name : Cancel
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject sp_activity_cancelwindow(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("sp_activity_cancelwindow"), anchor, flags);
	}
	
	/**
	 * Close: with default state.
	 *		.text : Close
	 * 		.class : .Pushbutton
	 * 		.state : 1048576
	 * 		.name : Close
	 * 		.classIndex : 0
	 */
	protected GuiTestObject sp_activity_close() 
	{
		return new GuiTestObject(
                        getMappedTestObject("sp_activity_close"));
	}
	/**
	 * Close: with specific test context and state.
	 *		.text : Close
	 * 		.class : .Pushbutton
	 * 		.state : 1048576
	 * 		.name : Close
	 * 		.classIndex : 0
	 */
	protected GuiTestObject sp_activity_close(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("sp_activity_close"), anchor, flags);
	}
	
	/**
	 * Options: with default state.
	 *		.text : RegularExpression(ACL 9|Options|Server*|Security*|Select|Data Definition*|.+)
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : RegularExpression(ACL 9|Options|Server*|Security*|Select*|Data Definition*|.+)
	 */
	protected TopLevelSubitemTestObject sp_activity_window() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("sp_activity_window"));
	}
	/**
	 * Options: with specific test context and state.
	 *		.text : RegularExpression(ACL 9|Options|Server*|Security*|Select|Data Definition*|.+)
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : RegularExpression(ACL 9|Options|Server*|Security*|Select*|Data Definition*|.+)
	 */
	protected TopLevelSubitemTestObject sp_activity_window(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("sp_activity_window"), anchor, flags);
	}
	
	

	protected keywordUtilHelper()
	{
		setScriptName("ACL_Desktop.AppObject.keywordUtil");
	}
	
}

