// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ACL_Desktop.TestCase.SmokeTest.Analyze;
import lib.acl.helper.TestCaseSuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>Statistics</b><br>
 * Generated     : <b>2012/03/24 3:49:10 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  March 24, 2012
 * @author Steven_Xiang
 */
public abstract class StatisticsHelper extends lib.acl.helper.TestCaseSuperHelper
{
	

	protected StatisticsHelper()
	{
		setScriptName("ACL_Desktop.TestCase.SmokeTest.Analyze.Statistics");
	}
	
}

