// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.lib.acl.tool;
import ACL_Desktop.AppObject.DesktopSuperHelper;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>_printObjects</b><br>
 * Generated     : <b>2012/10/22 2:27:23 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  October 22, 2012
 * @author Steven_Xiang
 */
public abstract class _printObjectsHelper extends ACL_Desktop.AppObject.DesktopSuperHelper
{
	/**
	 * CheckGUIStates1XlsCompatibilityMode: with default state.
	 *		.class : RegularExpression(EXCEL.*)
	 * 		.classIndex : 0
	 */
	protected FrameSubitemTestObject XLBook() 
	{
		return new FrameSubitemTestObject(
                        getMappedTestObject("XLBook"));
	}
	/**
	 * CheckGUIStates1XlsCompatibilityMode: with specific test context and state.
	 *		.class : RegularExpression(EXCEL.*)
	 * 		.classIndex : 0
	 */
	protected FrameSubitemTestObject XLBook(TestObject anchor, long flags) 
	{
		return new FrameSubitemTestObject(
                        getMappedTestObject("XLBook"), anchor, flags);
	}
	
	/**
	 * ComboBox: with default state.
	 *		.text : Do not repeat
	 * 		.class : ComboBox
	 * 		.name : Do not repeat
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject comboBoxcomboBox() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("comboBoxcomboBox"));
	}
	/**
	 * ComboBox: with specific test context and state.
	 *		.text : Do not repeat
	 * 		.class : ComboBox
	 * 		.name : Do not repeat
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject comboBoxcomboBox(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("comboBoxcomboBox"), anchor, flags);
	}
	
	/**
	 * DefineRange: with default state.
	 *		.text : Define Range
	 * 		.class : .Pushbutton
	 * 		.name : Define Range
	 * 		.classIndex : 0
	 */
	protected GuiTestObject defineRangebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("defineRangebutton"));
	}
	/**
	 * DefineRange: with specific test context and state.
	 *		.text : Define Range
	 * 		.class : .Pushbutton
	 * 		.name : Define Range
	 * 		.classIndex : 0
	 */
	protected GuiTestObject defineRangebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("defineRangebutton"), anchor, flags);
	}
	
	/**
	 * DocumentManager: with default state.
	 *		.text : null
	 * 		.class : DocumentManager
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject documentManagerwindow() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("documentManagerwindow"));
	}
	/**
	 * DocumentManager: with specific test context and state.
	 *		.text : null
	 * 		.class : DocumentManager
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject documentManagerwindow(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("documentManagerwindow"), anchor, flags);
	}
	
	/**
	 * MicrosoftExcelBook1: with default state.
	 *		.text : Microsoft Excel - Book1
	 * 		.class : XLMAIN
	 * 		.processName : EXCEL.EXE
	 * 		.name : Microsoft Excel - Book1
	 */
	protected TopLevelSubitemTestObject excelWin() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("excelWin"));
	}
	/**
	 * MicrosoftExcelBook1: with specific test context and state.
	 *		.text : Microsoft Excel - Book1
	 * 		.class : XLMAIN
	 * 		.processName : EXCEL.EXE
	 * 		.name : Microsoft Excel - Book1
	 */
	protected TopLevelSubitemTestObject excelWin(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("excelWin"), anchor, flags);
	}
	
	/**
	 * Grid: with default state.
	 *		.mappableClassIndex : 0
	 * 		.class : org.eclipse.nebula.widgets.grid.Grid
	 * 		.classIndex : 0
	 */
	protected ScrollTestObject grid() 
	{
		return new ScrollTestObject(
                        getMappedTestObject("grid"));
	}
	/**
	 * Grid: with specific test context and state.
	 *		.mappableClassIndex : 0
	 * 		.class : org.eclipse.nebula.widgets.grid.Grid
	 * 		.classIndex : 0
	 */
	protected ScrollTestObject grid(TestObject anchor, long flags) 
	{
		return new ScrollTestObject(
                        getMappedTestObject("grid"), anchor, flags);
	}
	
	/**
	 * lbxNumericColumns: with default state.
	 *		Name : lbxNumericColumns
	 * 		TabIndex : 7
	 * 		.class : System.Windows.Forms.CheckedListBox
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject lbxNumericColumnslist() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("lbxNumericColumnslist"));
	}
	/**
	 * lbxNumericColumns: with specific test context and state.
	 *		Name : lbxNumericColumns
	 * 		TabIndex : 7
	 * 		.class : System.Windows.Forms.CheckedListBox
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject lbxNumericColumnslist(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("lbxNumericColumnslist"), anchor, flags);
	}
	
	/**
	 * LogIn: with default state.
	 *		Name : EWPCasLogin
	 * 		Text : Log In
	 * 		TabIndex : 0
	 * 		.class : ACL.LightClient.ElectronicWorkPaper.EWPUtilities.UI.EWPCasLogin
	 * 		.processName : EXCEL.EXE
	 * 		.classIndex : 0
	 */
	protected TopLevelSubitemTestObject logInwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("logInwindow"));
	}
	/**
	 * LogIn: with specific test context and state.
	 *		Name : EWPCasLogin
	 * 		Text : Log In
	 * 		TabIndex : 0
	 * 		.class : ACL.LightClient.ElectronicWorkPaper.EWPUtilities.UI.EWPCasLogin
	 * 		.processName : EXCEL.EXE
	 * 		.classIndex : 0
	 */
	protected TopLevelSubitemTestObject logInwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("logInwindow"), anchor, flags);
	}
	
	/**
	 * lstRSCustomItems: with default state.
	 *		Name : lstRSCustomItems
	 * 		TabIndex : 0
	 * 		.class : System.Windows.Forms.ListBox
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject lstRSCustomItemslist() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("lstRSCustomItemslist"));
	}
	/**
	 * lstRSCustomItems: with specific test context and state.
	 *		Name : lstRSCustomItems
	 * 		TabIndex : 0
	 * 		.class : System.Windows.Forms.ListBox
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject lstRSCustomItemslist(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("lstRSCustomItemslist"), anchor, flags);
	}
	
	/**
	 * MicrosoftExcel: with default state.
	 *		.text : Microsoft Excel
	 * 		.class : XLMAIN
	 * 		.processName : EXCEL.EXE
	 * 		.name : Microsoft Excel
	 */
	protected TopLevelSubitemTestObject mew() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mew"));
	}
	/**
	 * MicrosoftExcel: with specific test context and state.
	 *		.text : Microsoft Excel
	 * 		.class : XLMAIN
	 * 		.processName : EXCEL.EXE
	 * 		.name : Microsoft Excel
	 */
	protected TopLevelSubitemTestObject mew(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("mew"), anchor, flags);
	}
	
	/**
	 * Outline: with default state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject outlinetree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("outlinetree"));
	}
	/**
	 * Outline: with specific test context and state.
	 *		.class : .Outline
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject outlinetree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("outlinetree"), anchor, flags);
	}
	
	/**
	 * Pagetablist: with default state.
	 *		.class : .Pagetablist
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject pagetablistpageTabList() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("pagetablistpageTabList"));
	}
	/**
	 * Pagetablist: with specific test context and state.
	 *		.class : .Pagetablist
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject pagetablistpageTabList(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("pagetablistpageTabList"), anchor, flags);
	}
	
	/**
	 * ProdCls8: with default state.
	 *		.text : Filter:
	 * 		.class : Edit
	 * 		.name : Filter:
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject prodCls8text() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("prodCls8text"));
	}
	/**
	 * ProdCls8: with specific test context and state.
	 *		.text : Filter:
	 * 		.class : Edit
	 * 		.name : Filter:
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject prodCls8text(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("prodCls8text"), anchor, flags);
	}
	
	/**
	 * Soundwave: with default state.
	 *		.class : .Pagetab
	 * 		.name : Soundwave
	 * 		.classIndex : 10
	 */
	protected GuiSubitemTestObject soundwavepageTab() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("soundwavepageTab"));
	}
	/**
	 * Soundwave: with specific test context and state.
	 *		.class : .Pagetab
	 * 		.name : Soundwave
	 * 		.classIndex : 10
	 */
	protected GuiSubitemTestObject soundwavepageTab(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("soundwavepageTab"), anchor, flags);
	}
	
	/**
	 * Summarize: with default state.
	 *		.text : Summarize
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : Summarize
	 */
	protected TopLevelSubitemTestObject summarizewindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("summarizewindow"));
	}
	/**
	 * Summarize: with specific test context and state.
	 *		.text : Summarize
	 * 		.class : #32770
	 * 		.processName : ACLWin.exe
	 * 		.name : Summarize
	 */
	protected TopLevelSubitemTestObject summarizewindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("summarizewindow"), anchor, flags);
	}
	
	/**
	 * SysListView32: with default state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject sysListView32table() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("sysListView32table"));
	}
	/**
	 * SysListView32: with specific test context and state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject sysListView32table(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("sysListView32table"), anchor, flags);
	}
	
	/**
	 * Table: with default state.
	 *		.class : .Table
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject tabletable() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("tabletable"));
	}
	/**
	 * Table: with specific test context and state.
	 *		.class : .Table
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject tabletable(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("tabletable"), anchor, flags);
	}
	
	/**
	 * Tree: with default state.
	 *		.mappableClassIndex : 0
	 * 		.class : org.eclipse.swt.widgets.Tree
	 * 		position : 171
	 * 		.classIndex : 0
	 */
	protected ScrollGuiSubitemTestObject tree() 
	{
		return new ScrollGuiSubitemTestObject(
                        getMappedTestObject("tree"));
	}
	/**
	 * Tree: with specific test context and state.
	 *		.mappableClassIndex : 0
	 * 		.class : org.eclipse.swt.widgets.Tree
	 * 		position : 171
	 * 		.classIndex : 0
	 */
	protected ScrollGuiSubitemTestObject tree(TestObject anchor, long flags) 
	{
		return new ScrollGuiSubitemTestObject(
                        getMappedTestObject("tree"), anchor, flags);
	}
	
	/**
	 * UndefineRange: with default state.
	 *		.text : Undefine Range
	 * 		.class : .Pushbutton
	 * 		.name : Undefine Range
	 * 		.classIndex : 1
	 */
	protected GuiTestObject undefineRangebutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("undefineRangebutton"));
	}
	/**
	 * UndefineRange: with specific test context and state.
	 *		.text : Undefine Range
	 * 		.class : .Pushbutton
	 * 		.name : Undefine Range
	 * 		.classIndex : 1
	 */
	protected GuiTestObject undefineRangebutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("undefineRangebutton"), anchor, flags);
	}
	
	/**
	 * SysTreeView32: with default state.
	 *		.text : null
	 * 		.class : SysTreeView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject wintree() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("wintree"));
	}
	/**
	 * SysTreeView32: with specific test context and state.
	 *		.text : null
	 * 		.class : SysTreeView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject wintree(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("wintree"), anchor, flags);
	}
	
	/**
	 * Working: with default state.
	 *		.text : Working
	 * 		.class : WindowsForms10.Window.8.app.0.2ea1a2
	 * 		.processName : EXCEL.EXE
	 * 		.name : Working
	 */
	protected TopLevelSubitemTestObject workingwindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("workingwindow"));
	}
	/**
	 * Working: with specific test context and state.
	 *		.text : Working
	 * 		.class : WindowsForms10.Window.8.app.0.2ea1a2
	 * 		.processName : EXCEL.EXE
	 * 		.name : Working
	 */
	protected TopLevelSubitemTestObject workingwindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("workingwindow"), anchor, flags);
	}
	
	

	protected _printObjectsHelper()
	{
		setScriptName("lib.acl.tool._printObjects");
	}
	
}

