// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.lib.acl.tool;
import lib.acl.helper.sup.MySuperHelper;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>convertCsvToXls</b><br>
 * Generated     : <b>2010/06/29 2:08:38 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  June 29, 2010
 * @author steven_xiang
 */
public abstract class convertCsvToXlsHelper extends lib.acl.helper.sup.MySuperHelper
{
	

	protected convertCsvToXlsHelper()
	{
		setScriptName("lib.acl.tool.convertCsvToXls");
	}
	
}

