// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.lib.acl.tool;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;

/**
 * Script Name   : <b>RFTObjectGetterGenerator</b><br>
 * Generated     : <b>2010/04/22 10:01:20 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 build 2600 Service Pack 3 <br>
 * 
 * @since  April 22, 2010
 * @author Henry_Wu
 */
public abstract class RFTObjectGetterGeneratorHelper extends RationalTestScript
{
	

	protected RFTObjectGetterGeneratorHelper()
	{
		setScriptName("lib.acl.tool.RFTObjectGetterGenerator");
	}
	
}

